### ISSUE TITLE
Add me as a co-owner!

### ISSUE THREAD

**Issue by chleongithub** [McFanta/McFanta.github.io#5]
i can improve the download site and create a site for mine and your maps

**Comment by McFanta** [comment]
Thanks for your suggestions. You can always help for now by sending a pull request if you have edited a html document. The site is basicly a personal site. In the future I am thinking about to create a map storage website with you? Sounds good? Leave your ideas!

**Comment by McFanta** [comment]
So I added you as collabrator. Before forking do not mess up the revisions page and contributing pages. I'll fix everything with the revisions logs. You can improve the downloads. But please let me know if you want major changes. I can do that!

**Comment by chleongithub** [comment]
Thanks!
